=== vdshivtsov/portfolio/xmlAndXslt/tabel_group.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tabel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="clerk">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="tabelGroup" />
							<xs:element type="xs:int" name="id" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="worker">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="tabelGroup" />
							<xs:element type="xs:string" name="snils" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:group name="tabelGroup">
		<xs:sequence>
			<xs:element type="xs:string" name="name" />
			<xs:element type="xs:date" name="birthday" />
		</xs:sequence>
	</xs:group>
</xs:schema>

=== vdshivtsov/portfolio/xmlAndXslt/tabel_group.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation="tabel_group.xsd">
	<clerk>
		<name>Vlad</name>
		<birthday>1989-09-21</birthday>
		<id>777</id>
	</clerk>
	<worker>
		<name>Petr</name>
		<birthday>1985-05-10</birthday>
		<snils>123456789</snils>
	</worker>
</tabel>
